#!/bin/bash

# make download 之后，make -j$(nproc) 之前执行

# General Settings

# 默认主机名
DF_NAME="XWRT"

# 默认地址
DF_IP="10.10.10.1"

# 默认密码
DF_WORD="password"











##############################################################

CFG_FILE="./package/base-files/files/bin/config_generate"

# 修改默认 IP 地址
sed -i "s/192\.168\.[0-9]*\.[0-9]*/$DF_IP/g" $CFG_FILE

# 修改默认主机名
sed -i "s/hostname='.*'/hostname='$DF_NAME'/g" $CFG_FILE

# 如果 DF_WORD 非空，并且 ./files/etc/uci-defaults/99-custom.sh 文件不存在
if [ -n "$DF_WORD" ] && [ ! -f "./files/etc/uci-defaults/99-custom.sh" ]; then
  # 创建 ./files/etc/uci-defaults/99-custom.sh 文件并写入命令
  mkdir -p ./files/etc/uci-defaults
  echo -e "(echo \"$DF_WORD\"; sleep 1; echo \"$DF_WORD\") | passwd > /dev/null" > ./files/etc/uci-defaults/99-custom.sh
  chmod +x ./files/etc/uci-defaults/99-custom.sh
fi
echo "配置已更新！"

