#!/bin/bash

# 提示是否运行 diy.sh
read -p "是否运行 diy.sh？选择 Y/y 继续，N/n 跳过: " run_diy
if [[ "$run_diy" == "Y" || "$run_diy" == "y" ]]; then
    sudo docker exec -it -u user -w /home/user/openwrt openwrt_build bash -c "./diy.sh"
    sudo docker exec -it -u user -w /home/user/openwrt openwrt_build bash -c "./scripts/feeds update -a && ./scripts/feeds install -a"
fi

# 提示是否运行 make menuconfig
read -p "是否运行 make menuconfig？选择 Y/y 继续，N/n 跳过: " run_menuconfig
if [[ "$run_menuconfig" == "Y" || "$run_menuconfig" == "y" ]]; then
    sudo docker exec -u user -w /home/user/openwrt openwrt_build bash -c "sudo apt-get update && sudo apt-get install -y screen"
    sudo docker exec -it -u user -w /home/user/openwrt openwrt_build bash -c "screen make menuconfig"
fi

# 生成diffconfig文件
sudo docker exec -it -u user -w /home/user/openwrt openwrt_build bash -c "./scripts/diffconfig.sh > diffconfig"
sudo docker exec -it -u user -w /home/user/openwrt openwrt_build bash -c "ls -l diffconfig"


# 从容器内复制 diffconfig 文件到本机 ./target 目录
sudo docker cp openwrt_build:/home/user/openwrt/diffconfig ./target/diffconfig

# 输出复制结果
ls -l ./target/diffconfig


