
name: DEL TAG 

on:
  # 手动触发
  workflow_dispatch:

jobs:
  Get_config_Building:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Drop orphan tags
        continue-on-error: true
        uses: jay2610/delete-older-releases@1.0.0
        with:
          keep_latest: 3
          delete_tag_pattern: beta # defaults to ""
          delete_type: 'release'
          target_branch: 'master'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
