name: OpenWrt Build with Cache

on:
  push:
    branches:
      - main  # 你可以根据需要更改分支名
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # 运行在最新的 Ubuntu 环境

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v2

      # 设置 Docker 构建环境
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 缓存 OpenWrt 编译相关的文件夹（dl、build_dir、staging_dir）
      - name: Cache OpenWrt build directories
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/openwrt/dl
            ${{ github.workspace }}/openwrt/build_dir
            ${{ github.workspace }}/openwrt/staging_dir
          key: ${{ runner.os }}-openwrt-${{ hashFiles('**/Makefile') }}
          restore-keys: |
            ${{ runner.os }}-openwrt-

      # 设置 Docker 镜像
      - name: Set up Docker environment for OpenWrt
        run: |
          docker pull debian:11

      # 在 Docker 容器中编译 OpenWrt
      - name: Build OpenWrt
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace debian:11 bash -c "
            apt-get update -qq && apt-get install -qqy --no-install-recommends \
              build-essential git rsync curl sudo python3 python3-pip \
              zlib1g-dev libncurses-dev libssl-dev && \
            git clone https://github.com/openwrt/openwrt.git && \
            cd openwrt && \
            ./scripts/feeds update -a && \
            ./scripts/feeds install -a && \
            cp /workspace/diy.sh . && \
            bash diy.sh && \
            make defconfig && \
            make -j$(nproc) || make -j1 V=s
          "

      # 缓存编译成果
      - name: Cache OpenWrt build output
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/openwrt/bin
            ${{ github.workspace }}/openwrt/tmp
          key: ${{ runner.os }}-openwrt-build-${{ hashFiles('**/Makefile') }}
          restore-keys: |
            ${{ runner.os }}-openwrt-build-
      
      # 上传构建的固件文件
      - name: Upload OpenWrt firmware
        uses: actions/upload-artifact@v2
        with:
          name: openwrt-firmware
          path: ${{ github.workspace }}/openwrt/bin/targets/*/*.img
