name: Build OpenWRT In Dcoker

on:
  # 手动触发
  workflow_dispatch:
  # 定时触发 (例如每天凌晨 1 点触发)
#  schedule:
#    - cron: '0 1 * * *'  # 每天凌晨 1 点 UTC，按需求调整时间

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in ./artifacts
        #if: false  # 跳过该步骤
        if: true  # 该步骤会执行
        run: |
          echo "Show disk space"
          echo "=============================================================================="
          df -hT
          echo "=============================================================================="
  
      - name: Download artifacts
        uses: actions/download-artifact@main
        with:
          path: ./artifacts/

      - name: List files in ./artifacts
        #if: false  # 跳过该步骤
        if: true  # 该步骤会执行
        run: |
          echo "Show disk space"
          echo "=============================================================================="
          df -hT
          echo "=============================================================================="
          
      - name: Unzip all artifact files
        run: |
          # 解压 ./artifacts/ 目录及其子目录中的所有 .zip 文件
          shopt -s globstar  # 开启 globstar 以支持 ** 递归匹配
          for zip_file in ./artifacts/**/*.zip; do
            if [[ -f "$zip_file" ]]; then
              echo "Unzipping $zip_file..."
              unzip "$zip_file" -d ./artifacts/  # 解压到 ./artifacts/ 目录
              rm "$zip_file"  # 删除 .zip 文件
            fi
          done

          
      - name: List files in ./artifacts
        #if: false  # 跳过该步骤
        if: true  # 该步骤会执行
        run: |
          echo "Show disk space"
          echo "=============================================================================="
          df -hT
          echo "=============================================================================="
  
      - name: Create Git tag
        id: create_tag
        run: |
          # 设置标签名
          TAG_NAME="发布时间(UTC+8)：$(TZ="Asia/Shanghai" date +'%Y.%m.%d-%H_%M')"
          RELEASE_NAME="发布时间(UTC+8)：$(TZ="Asia/Shanghai" date +'%Y-%m-%d %H:%M')"
          
          # 输出标签名和发布名
          echo "TAG_NAME=${TAG_NAME}"
          echo "RELEASE_NAME=${RELEASE_NAME}"

          # 将标签名和发布名传递给后续步骤
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
          echo "RELEASE_NAME=${RELEASE_NAME}" >> $GITHUB_ENV
          
          # 配置 Git 用户
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # 创建标签
          git tag $TAG_NAME

          # 推送标签到远程仓库
          git push origin $TAG_NAME
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }} $TAG_NAME          

      - name: Set up GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.RELEASE_NAME }}
          files: ./artifacts/**/*  # 递归匹配所有文件
          body: "Release with multiple builds"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             
      - name: Delete old workflow runs
        run: |
          echo "Deleting old workflow runs..."
          WORKFLOW_RUNS=$(curl -s -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs")
          RUN_IDS=$(echo $WORKFLOW_RUNS | jq '.workflow_runs | sort_by(.created_at) | reverse | .[3:] | .[].id')
          for RUN_ID in $(echo $RUN_IDS); do
            echo "Deleting workflow run: $RUN_ID"
            curl -X DELETE -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID"
          done

      - name: Delete old releases
        run: |
          echo "Deleting old releases..."
          RELEASES=$(curl -s -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/releases")
          RELEASE_IDS=$(echo $RELEASES | jq '. | sort_by(.created_at) | reverse | .[3:] | .[].id')
          for RELEASE_ID in $(echo $RELEASE_IDS); do
            RELEASE_NAME=$(echo $RELEASES | jq -r ".[] | select(.id == $RELEASE_ID) | .name")
            echo "Deleting release: $RELEASE_NAME"
            curl -X DELETE -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID"
          done

      - name: Delete old tags
        run: |
          echo "Deleting old tags..."
          TAGS=$(curl -s -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/tags")
          TAG_NAMES=$(echo $TAGS | jq -r '.[] | {name: .name, date: (.name | match("[0-9]{4}.[0-9]{2}.[0-9]{2}-[0-9]{2}_[0-9]{2}") | .string)} | select(.date != null) | .name' | sort)
          TAG_NAMES=$(echo "$TAG_NAMES" | head -n -3)
          for TAG_NAME in $(echo "$TAG_NAMES"); do
            echo "Deleting tag: $TAG_NAME"
            curl -X DELETE -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/git/refs/tags/$TAG_NAME"
          done

      - name: Delete all files in ./artifacts
        #if: false  # 跳过该步骤
        if: true  # 该步骤会执行
        run: |
          echo "Deleting all files in ./artifacts..."
          rm -rf ./artifacts/*
