
name: TEST

on:
  # 手动触发
  workflow_dispatch:
  # 定时触发 (例如每天凌晨 1 点触发)
#  schedule:
#    - cron: '0 1 * * *'  # 每天凌晨 1 点 UTC，按需求调整时间

jobs:
  Get_config_Building:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        version: [openwrt]
        #version: [lienol]
        #branch: [openwrt-24.10, openwrt-23.10]  # 默认分支
        branch: [openwrt-24.10]
        # 如果 version 为 lede，默认分支将是 main，稍后调整
        platform: [x86_64]
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Determine branch
        id: set_branch
        run: |
          if [[ "${{ matrix.version }}" == "immortalwrt" || "${{ matrix.version }}" == "openwrt" ]]; then
            echo "branch=${{ matrix.branch }}" >> $GITHUB_ENV
          elif [[ "${{ matrix.version }}" == "lede" ]]; then
            if [[ "${{ matrix.branch }}" == "openwrt-24.10" ]]; then
              echo "branch=master" >> $GITHUB_ENV
            else
              exit 0
            fi
          elif [[ "${{ matrix.version }}" == "lienol" ]]; then
            branch_name=$(echo "${{ matrix.branch }}" | sed 's/^openwrt-//')
            echo "branch=${branch_name}" >> $GITHUB_ENV
          fi
     
      - name: diffconfig.bak
        run: |
          # 创建目标目录        
          mkdir -p ./target/
          echo "test1" > ./target/diffconfig.bak      

                
      - name: SSH远程连接（点击 "Web shell:" 链接后键入"q"方才显示终端；进入终端后执行："./mv"，所有设置完成后，键入“exit”退出）
        if: false  # 跳过该步骤
        uses: mxschmitt/action-tmate@v3

      - name: Commit and push files to the repository
        run: |
          # 创建目标目录
          
          mkdir -p ./${{ matrix.version }}/${{ env.branch }}/${{ matrix.platform }}

          # 仅复制 /target/ 中的内容到目标目录
          cp -r ./target/* ./${{ matrix.version }}/${{ env.branch }}/${{ matrix.platform }}/

          # 配置 Git 用户
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # 进入仓库的根目录，并确保目标路径下的文件被添加到 Git
          git add ./${{ matrix.version }}/${{ env.branch }}/${{ matrix.platform }}/*

          # 提交更改
          git commit -m "Add build artifacts"
          
          git push origin ${{ github.ref }} || git pull --rebase origin ${{ github.ref }}
         

